insert into languages (code, name, family, priority) values
  ('sw', 'Kiswahili', 'Bantu', 'priority'),
  ('en', 'Kenyan English', 'English', 'seeded'),
  ('sheng', 'Sheng', 'Urban mixed', 'priority'),
  ('kikuyu', 'Kikuyu', 'Bantu', 'priority'),
  ('kamba', 'Kamba', 'Bantu', 'priority'),
  ('dholuo', 'Dholuo', 'Nilotic', 'priority'),
  ('luhya', 'Luhya', 'Bantu', 'priority'),
  ('bukusu', 'Bukusu', 'Bantu', 'seeded'),
  ('maragoli', 'Maragoli', 'Bantu', 'seeded'),
  ('wanga', 'Wanga', 'Bantu', 'seeded'),
  ('tachoni', 'Tachoni', 'Bantu', 'seeded'),
  ('idakho', 'Idakho', 'Bantu', 'seeded'),
  ('isukha', 'Isukha', 'Bantu', 'seeded'),
  ('tiriki', 'Tiriki', 'Bantu', 'seeded'),
  ('gusii', 'Gusii', 'Bantu', 'priority'),
  ('kuria', 'Kuria', 'Bantu', 'seeded'),
  ('meru', 'Meru', 'Bantu', 'priority'),
  ('embu', 'Embu', 'Bantu', 'seeded'),
  ('mbeere', 'Mbeere', 'Bantu', 'seeded'),
  ('tharaka', 'Tharaka', 'Bantu', 'seeded'),
  ('chuka', 'Chuka', 'Bantu', 'seeded'),
  ('giri', 'Giriama', 'Mijikenda', 'priority'),
  ('digo', 'Digo', 'Mijikenda', 'priority'),
  ('duruma', 'Duruma', 'Mijikenda', 'seeded'),
  ('chonyi', 'Chonyi', 'Mijikenda', 'seeded'),
  ('jibana', 'Jibana', 'Mijikenda', 'seeded'),
  ('kambe', 'Kambe', 'Mijikenda', 'seeded'),
  ('kauma', 'Kauma', 'Mijikenda', 'seeded'),
  ('rabai', 'Rabai', 'Mijikenda', 'seeded'),
  ('ribe', 'Ribe', 'Mijikenda', 'seeded'),
  ('poko', 'Pokomo', 'Bantu', 'priority'),
  ('taita', 'Taita', 'Bantu', 'seeded'),
  ('taveta', 'Taveta', 'Bantu', 'seeded'),
  ('dawida', 'Dawida', 'Bantu', 'seeded'),
  ('sagalla', 'Sagalla', 'Bantu', 'seeded'),
  ('segeju', 'Segeju', 'Bantu', 'seeded'),
  ('kipsigis', 'Kipsigis', 'Kalenjin', 'seeded'),
  ('nandi', 'Nandi', 'Kalenjin', 'seeded'),
  ('keiyo', 'Keiyo', 'Kalenjin', 'seeded'),
  ('marakwet', 'Marakwet', 'Kalenjin', 'seeded'),
  ('tugen', 'Tugen', 'Kalenjin', 'seeded'),
  ('pokot', 'Pokot', 'Kalenjin', 'seeded'),
  ('sabaot', 'Sabaot', 'Kalenjin', 'seeded'),
  ('terik', 'Terik', 'Kalenjin', 'endangered'),
  ('ogiek', 'Ogiek', 'Kalenjin', 'endangered'),
  ('maasai', 'Maasai', 'Maa', 'priority'),
  ('samburu', 'Samburu', 'Maa', 'seeded'),
  ('ilchamus', 'Ilchamus', 'Maa', 'endangered'),
  ('turk', 'Turkana', 'Ateker', 'priority'),
  ('somali', 'Somali', 'Cushitic', 'priority'),
  ('borana', 'Borana', 'Cushitic', 'seeded'),
  ('rendille', 'Rendille', 'Cushitic', 'seeded'),
  ('orma', 'Orma', 'Cushitic', 'seeded'),
  ('gabra', 'Gabra', 'Cushitic', 'seeded'),
  ('burji', 'Burji', 'Cushitic', 'endangered'),
  ('sakuye', 'Sakuye', 'Cushitic', 'endangered'),
  ('garre', 'Garre', 'Cushitic', 'seeded'),
  ('aweer', 'Aweer / Boni', 'Cushitic', 'endangered'),
  ('dahalo', 'Dahalo', 'Cushitic', 'endangered'),
  ('yaaku', 'Yaaku', 'Cushitic', 'endangered'),
  ('elmolo', 'El Molo', 'Cushitic', 'endangered'),
  ('daasanach', 'Daasanach', 'Cushitic', 'seeded'),
  ('suba', 'Suba', 'Bantu', 'endangered'),
  ('bajuni', 'Bajuni', 'Bantu', 'seeded'),
  ('nubian', 'Kenyan Nubian', 'Nubian', 'seeded'),
  ('arabic', 'Kenyan Arabic', 'Semitic', 'seeded'),
  ('gujarati', 'Gujarati Kenya', 'Indo-Aryan', 'seeded'),
  ('hindi', 'Hindi Kenya', 'Indo-Aryan', 'seeded')
on conflict (code) do update set
  name = excluded.name,
  family = excluded.family,
  priority = excluded.priority,
  active = true;
