export type LanguagePriority = "priority" | "seeded" | "endangered";

export type SemaLanguage = {
  code: string;
  name: string;
  family: string;
  priority: LanguagePriority;
};

export const LANGUAGES: SemaLanguage[] = [
  { code: "sw", name: "Kiswahili", family: "Bantu", priority: "priority" },
  { code: "en", name: "Kenyan English", family: "English", priority: "seeded" },
  { code: "sheng", name: "Sheng", family: "Urban mixed", priority: "priority" },
  { code: "kikuyu", name: "Kikuyu", family: "Bantu", priority: "priority" },
  { code: "kamba", name: "Kamba", family: "Bantu", priority: "priority" },
  { code: "dholuo", name: "Dholuo", family: "Nilotic", priority: "priority" },
  { code: "luhya", name: "Luhya", family: "Bantu", priority: "priority" },
  { code: "bukusu", name: "Bukusu", family: "Bantu", priority: "seeded" },
  { code: "maragoli", name: "Maragoli", family: "Bantu", priority: "seeded" },
  { code: "wanga", name: "Wanga", family: "Bantu", priority: "seeded" },
  { code: "tachoni", name: "Tachoni", family: "Bantu", priority: "seeded" },
  { code: "idakho", name: "Idakho", family: "Bantu", priority: "seeded" },
  { code: "isukha", name: "Isukha", family: "Bantu", priority: "seeded" },
  { code: "tiriki", name: "Tiriki", family: "Bantu", priority: "seeded" },
  { code: "gusii", name: "Gusii", family: "Bantu", priority: "priority" },
  { code: "kuria", name: "Kuria", family: "Bantu", priority: "seeded" },
  { code: "meru", name: "Meru", family: "Bantu", priority: "priority" },
  { code: "embu", name: "Embu", family: "Bantu", priority: "seeded" },
  { code: "mbeere", name: "Mbeere", family: "Bantu", priority: "seeded" },
  { code: "tharaka", name: "Tharaka", family: "Bantu", priority: "seeded" },
  { code: "chuka", name: "Chuka", family: "Bantu", priority: "seeded" },
  { code: "giri", name: "Giriama", family: "Mijikenda", priority: "priority" },
  { code: "digo", name: "Digo", family: "Mijikenda", priority: "priority" },
  { code: "duruma", name: "Duruma", family: "Mijikenda", priority: "seeded" },
  { code: "chonyi", name: "Chonyi", family: "Mijikenda", priority: "seeded" },
  { code: "jibana", name: "Jibana", family: "Mijikenda", priority: "seeded" },
  { code: "kambe", name: "Kambe", family: "Mijikenda", priority: "seeded" },
  { code: "kauma", name: "Kauma", family: "Mijikenda", priority: "seeded" },
  { code: "rabai", name: "Rabai", family: "Mijikenda", priority: "seeded" },
  { code: "ribe", name: "Ribe", family: "Mijikenda", priority: "seeded" },
  { code: "poko", name: "Pokomo", family: "Bantu", priority: "priority" },
  { code: "taita", name: "Taita", family: "Bantu", priority: "seeded" },
  { code: "taveta", name: "Taveta", family: "Bantu", priority: "seeded" },
  { code: "dawida", name: "Dawida", family: "Bantu", priority: "seeded" },
  { code: "sagalla", name: "Sagalla", family: "Bantu", priority: "seeded" },
  { code: "segeju", name: "Segeju", family: "Bantu", priority: "seeded" },
  { code: "kipsigis", name: "Kipsigis", family: "Kalenjin", priority: "seeded" },
  { code: "nandi", name: "Nandi", family: "Kalenjin", priority: "seeded" },
  { code: "keiyo", name: "Keiyo", family: "Kalenjin", priority: "seeded" },
  { code: "marakwet", name: "Marakwet", family: "Kalenjin", priority: "seeded" },
  { code: "tugen", name: "Tugen", family: "Kalenjin", priority: "seeded" },
  { code: "pokot", name: "Pokot", family: "Kalenjin", priority: "seeded" },
  { code: "sabaot", name: "Sabaot", family: "Kalenjin", priority: "seeded" },
  { code: "terik", name: "Terik", family: "Kalenjin", priority: "endangered" },
  { code: "ogiek", name: "Ogiek", family: "Kalenjin", priority: "endangered" },
  { code: "maasai", name: "Maasai", family: "Maa", priority: "priority" },
  { code: "samburu", name: "Samburu", family: "Maa", priority: "seeded" },
  { code: "ilchamus", name: "Ilchamus", family: "Maa", priority: "endangered" },
  { code: "turk", name: "Turkana", family: "Ateker", priority: "priority" },
  { code: "somali", name: "Somali", family: "Cushitic", priority: "priority" },
  { code: "borana", name: "Borana", family: "Cushitic", priority: "seeded" },
  { code: "rendille", name: "Rendille", family: "Cushitic", priority: "seeded" },
  { code: "orma", name: "Orma", family: "Cushitic", priority: "seeded" },
  { code: "gabra", name: "Gabra", family: "Cushitic", priority: "seeded" },
  { code: "burji", name: "Burji", family: "Cushitic", priority: "endangered" },
  { code: "sakuye", name: "Sakuye", family: "Cushitic", priority: "endangered" },
  { code: "garre", name: "Garre", family: "Cushitic", priority: "seeded" },
  { code: "aweer", name: "Aweer / Boni", family: "Cushitic", priority: "endangered" },
  { code: "dahalo", name: "Dahalo", family: "Cushitic", priority: "endangered" },
  { code: "yaaku", name: "Yaaku", family: "Cushitic", priority: "endangered" },
  { code: "elmolo", name: "El Molo", family: "Cushitic", priority: "endangered" },
  { code: "daasanach", name: "Daasanach", family: "Cushitic", priority: "seeded" },
  { code: "suba", name: "Suba", family: "Bantu", priority: "endangered" },
  { code: "bajuni", name: "Bajuni", family: "Bantu", priority: "seeded" },
  { code: "nubian", name: "Kenyan Nubian", family: "Nubian", priority: "seeded" },
  { code: "arabic", name: "Kenyan Arabic", family: "Semitic", priority: "seeded" },
  { code: "gujarati", name: "Gujarati Kenya", family: "Indo-Aryan", priority: "seeded" },
  { code: "hindi", name: "Hindi Kenya", family: "Indo-Aryan", priority: "seeded" }
];

export const languageFamilies = Array.from(new Set(LANGUAGES.map((language) => language.family))).sort();
